import type { components } from '../generated/openapi.js';

type S = components['schemas'];
export type LanguageCode = S['TranscriptionLanguageCodeEnum'];
export type TranslationLanguageCode = S['TranslationLanguageCodeEnum'];
export type LanguageConfig = S['LanguageConfig'];
export type CustomVocabularyEntry = S['CustomVocabularyEntryDTO'];
export type CustomVocabularyConfig = S['CustomVocabularyConfigDTO'];
export type DiarizationConfig = S['DiarizationConfigDTO'];
export type SubtitleFormat = S['SubtitlesFormatEnum'];
export type SubtitleStyle = S['SubtitlesStyleEnum'];
export type SubtitlesConfig = S['SubtitlesConfigDTO'];
export type TranslationModel = S['TranslationModelEnum'];
export type TranslationConfig = S['TranslationConfigDTO'];
export type SummarizationType = S['SummaryTypesEnum'];
export type SummarizationConfig = S['SummarizationConfigDTO'];
export type CustomSpellingConfig = S['CustomSpellingConfigDTO'];
export type AudioToLlmConfig = S['AudioToLlmListConfigDTO'];
export type PiiEntityType = S['PiiRedactionEntityTypeEnum'];
export type PiiProcessedTextType = NonNullable<S['PiiRedactionConfigDTO']['processed_text_type']>;
export type PiiRedactionConfig = S['PiiRedactionConfigDTO'];
export type CallbackMethod = S['CallbackMethodEnum'];
export type CallbackConfig = S['CallbackConfigDto'];
export type PreProcessingConfig = S['PreProcessingConfig'];
export type RealtimeProcessingConfig = S['RealtimeProcessingConfig'];
export type PostProcessingConfig = S['PostProcessingConfig'];
export type MessagesConfig = S['MessagesConfig'];
export type LiveCallbackConfig = S['CallbackConfig'];
