import type { components } from '../generated/openapi.js';
type S = components['schemas'];
export type LiveEncoding = S['StreamingSupportedEncodingEnum'];
export type LiveBitDepth = S['StreamingSupportedBitDepthEnum'];
export type LiveSampleRate = S['StreamingSupportedSampleRateEnum'];
export type LiveModel = S['StreamingSupportedModels'];
export type LiveRegion = S['StreamingSupportedRegions'];
export type LiveRequest = S['StreamingRequest'];
export type LiveCreatedResponse = S['InitStreamingResponse'];
export type LiveRequestParams = S['StreamingRequestParamsResponse'];
export type LiveTranscriptionResult = S['StreamingTranscriptionResultWithMessagesDTO'];
export type LiveResponse = S['StreamingResponse'];
export type ListLiveResponse = S['ListStreamingResponse'];
export type PatchLiveRequest = S['PatchRequestParamsDTO'];
